### ISSUE TITLE
RailCraft Issues

### ISSUE THREAD

**Issue by MoraglarKhilen** [AlmuraDev/GameServer#9] opened 2018-05-23 20:29 UTC
Blast furnace (BF) does not burn. Correctly prevents anything but coke or charcoal (Not Blocks, dont know if bug or not) from being placed in BF but does not show flame in interface or outside block animations and does not process ingots into steel.

Iron Tanks when placed in a bunch of different (allowable) configurations do not form the multi-block tank. Steel Tanks do work so its not my inability to follow tank directions :)
However Steel Tanks when used with BC fluid pipes to pump creosote from coke oven doesn't remove the creosote from the pipe but does keep adding it to the Tank generating a lot of it when using gold/diamond pipes. same with wooden/cobblestone pipe. watching a very little of fluid ebb back and forth in the pipe causes it generate fluid in tank when press against the valve and stops when sloshes away.  (I played with this for awhile to trying to ascertain what was happening.)

**Comment by liach** [comment] 2018-05-24 02:19
are you pumping to the valve?

**Comment by MoraglarKhilen** [comment] 2018-05-24 02:39
yes tried with a wooden then cobble fluid pipe and a wooden/diamond then gold
redstone engine powering the extraction pipes in either case

**Comment by liach** [comment] 2018-05-24 03:15
@MoraglarKhilen Try pump in fluid only at top and on sides and only drain from the bottom and sides.

**Comment by MoraglarKhilen** [comment] 2018-05-24 03:29
NO change fluid still doesnt actually leave pipe into tank but tank fills with creosote havent tried other fluids yet

**Comment by liach** [comment] 2018-05-24 03:32
So fluid dupes in tank?

**Comment by MoraglarKhilen** [comment] 2018-05-24 03:38
yes liquid still registers in tank multiplying the liquid rapidly and having pumped it out confirms it,

**Comment by liach** [comment] 2018-05-24 04:33
@MoraglarKhilen Does this happen with buildcraft tanks?

**Comment by MoraglarKhilen** [comment] 2018-05-24 18:07
No it doesnt.  I used BC tanks to move water and lava back and forth between Steel Tanks trying different liquids

**Comment by liach** [comment] 2018-05-24 18:20
What I see is that bc pipe is still supplying creosote after the source of creosote, a bc glass tank, is drained completely. The source was drained before. @alexiil can you help?

**Comment by AlexIIL** [comment] 2018-05-26 14:02
What blocks are interacting here? I can't quite tell what exactly is going on from your descriptions, could some-one post a screenshot?

**Comment by liach** [comment] 2018-05-26 14:29
Hmm, don't have one right now. Steps of replication:
1. Place a rc iron tank multiblock and a bc glass tank connected with a wooden fluid pipe.
2. tweak the pipe to drain from bc tank. add a redstone engine to the pipe.
3. Put a lot of creosote (like 16 buckets or so) into the bc tank. Observe the pipe draining from bc tank to rc tank as usual.
4. When the bc tank is empty, the pipe keeps draining and the rc tank keeps filling.

**Comment by AlexIIL** [comment] 2018-05-26 14:41
That sounds a lot like the internal delay that BC fluid pipes have. (They act a bit like lots of little tanks, and they move fluid from one tank to the next until everything has drained).

Unless of course the rc tank gets more than 16 buckets of creosote. In that case I'd assume that one of the handlers wasn't written quite right, and duplicated fluid.

**Comment by liach** [comment] 2018-05-26 14:42
rc tank does get over 16 buckets of creosote.

**Comment by AlexIIL** [comment] 2018-05-26 14:43
Ah, ok.

**Comment by liach** [comment] 2018-05-26 14:50
by the way, the motion of the engine stops but the fluid level in the pipe remains and the fluid's texture is flowing

**Comment by AlexIIL** [comment] 2018-05-26 14:55
Yes, that's normal bc fluid pipe behaviour - the engine stops as the supplier  tank is empty, but the pipe still contains fluids to be moved

**Comment by AlexIIL** [comment] 2018-05-26 14:57
What versions of these mods are being used?

**Comment by liach** [comment] 2018-05-26 15:02
It happens within the dev env of railcraft (that is the head of liach-1.12.2) and bc version is here: https://github.com/Railcraft/Railcraft/blob/liach-1.12.2/version/gradle.properties#L4

**Comment by AlexIIL** [comment] 2018-05-26 15:58
It looks like the issue is https://github.com/Railcraft/Railcraft/blob/liach-1.12.2/src/main/java/mods/railcraft/common/blocks/multi/TileTankIronValve.java#L156-L165 always returning 0, rather than the amount of fluid that was put into the tank, which makes buildcraft think that no fluid was accepted by the valve. I assume the steel valve is broken in the same way.

**Comment by liach** [comment] 2018-05-27 01:04
Will check if it's fixed.

**Comment by MoraglarKhilen** [comment] 2018-05-30 03:06
I tested with steel tank moving cresote lava and water. no duplication. 
iron tank pieces form the multiblock tank and the blast furnace is accepting fuel and creating steel.

**Comment by liach** [comment] 2018-09-19 00:25
doc, you can close this now. fixed on rc's end long ago

**Closed as completed** 2018-09-19 00:27 UTC
